export const styles = {
    firstPageContainer: {
        height: '100vh',
        display: 'flex',
        backgroundColor: '#77C9D4',
        backgroundImage: 'linear-gradient(to right, #77C9D4, #57BC90)',
    },
    firstPageContentContainer: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    image: {
        width: '100%',
        '& img': {
            width: '100%',
        },
    },
    nameText: {
        fontSize: '2.5rem',
        color: '#015249',
        fontWeight: '600',
        textAlign: 'center',
    },
    myNameText: {
        color: 'white',
    },
    welcomeText: {
        fontSize: '1.5rem',
        marginTop: '1rem',
        fontWeight: '500',
        color: '#015249',
        textAlign: 'center',
    },
    buttonContainer: {
        display: 'flex',
        justifyContent: 'center',
        marginTop: '2rem',
    },
    button: {
        display: 'flex',
        backgroundColor: '#015249',
        margin: '1rem',
        borderRadius: '10rem',
        alignSelf: 'center',
    },
    pageTwoContainer: {
        height: '100vh',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: 'white',
    },
    titleContainer: {
        display: 'flex',
        flexDirection: 'column',
        width: '100%',
        alignContent: 'center',
    },
    title: {
        margin: '2rem auto 1rem auto',
        color: '#015249',
        fontWeight: '600',
        fontSize: '4rem',
    },
    divider: {
        color: 'black',
        margin: '0 auto',
        width: '10rem',
        borderBottomWidth: '0.2rem',
        backgroundColor: 'rgba(28, 162, 178, 0.3)',
    },
    contentContainer: {
        width: '100rem',
        display: 'flex',
        justifyContent: 'center',
        margin: '6rem auto',
    },
    aboutMeCard: {
        display: 'flex',
        flexDirection: 'column',
        borderRadius: '0.5rem',
        maxHeight: '25rem',
        width: '20rem',
        margin: '2rem',
        textAlign: 'center',
        alignItems: 'center',
        boxShadow: 'rgba(0, 0, 0, 0.35) 0px 5px 15px',
    },
    aboutMeIcon: {
        height: '3.5rem',
        fontSize: '2.5rem',
        margin: '1rem 0rem',
    },
    aboutMeTitleText: {
        fontSize: '1.5rem',
        width: '100%',
        fontWeight: '600',
        marginBottom: '2.5rem',
        color: '#1CA2B2',
    },
    aboutMeDescription: {
        fontSize: '1rem',
        height: '12rem',
        margin: '0rem 3rem',
        color: '#323333',
    },
    pageThreeContainer: {
        height: '100vh',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: 'white',
    },
    workCard: {
        display: 'flex',
        width: '50rem',
        height: '25rem',
        backgroundColor: 'rgba(1, 82, 73, 0.25)',
        borderRadius: '0.5rem',
        margin: '3rem 0rem',
    },
    workCardImageContainer: {
        width: '50%',
        margin: 'auto',
        textAlign: 'center',
    },
    workCardImage: {
        width: '15rem',
        height: '15rem',
    },
    workCardContent: {
        width: '50%',
        padding: '1rem',
    },
    dividerStyle: {
        height: '20rem',
        marginTop: '2rem',
        borderRightWidth: '0.15rem',
        backgroundColor: 'white',
    },
    workCardTitle: {
        fontSize: '1.4rem',
        fontWeight: '600',
        marginTop: '2rem',
        color: '#323333',
        textShadow: '1px 1px 0px white',
    },
    workCardRole: {
        fontSize: '1.2rem',
        fontWeight: '500',
        color: '#1CA2B2',
        margin: '0.2rem 0rem',
    },
    workCardLocation: {
        fontSize: '1rem',
        color: '#F6F6F6',
    },
    workCardDate: {
        fontSize: '1rem',
        color: '#F6F6F6',
        marginBottom: '1rem',
    },
    workCardDescription: {
        fontSize: '1.2rem',
        color: '#1B1B1B',
    },
    pageFourContainer: {
        height: '100vh',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: 'white',
    },
    projectCardContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        padding: '1rem',
    },
    projectCard: {
        boxShadow: 'rgba(0, 0, 0, 0.35) 0px 5px 15px',
        width: '20rem',
        height: '20rem',
        marginBottom: '2rem',
    },
    projectCardImage: {
        width: '100%',
        opacity: '90%',
        '&:hover': {
            opacity: '100%',
        },
    },
}